name: Build
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Release Social Playlist
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/libs/social-playlist-0.0.1-SNAPSHOT.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Install and Build Documentation
        working-directory: docs
        run: |
          npm install
          npm run build

      - name: Deploy Documentation
        uses: JamesIves/github-pages-deploy-action@4.1.2
        if: github.ref == 'refs/heads/main'
        with:
          branch: gh-pages
          folder: docs/src/.vuepress/dist
